# Generated by Django 4.2.9 on 2024-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_price', models.IntegerField()),
                ('mobile_brand', models.CharField(max_length=50)),
                ('mobile_spec', models.TextField(max_length=200)),
                ('mobile_img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
